networks:
  app-tier:
    driver: bridge

services:
  postgres:
    image: docker.io/bitnami/postgresql:latest
    ports:
      - "5432:5432"
    networks:
      - app-tier
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos_cms

  minio:
    image: docker.io/bitnami/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-tier
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=123456
      - MINIO_DEFAULT_BUCKETS=images,videos,avatars
      - MINIO_FORCE_NEW_KEYS=yes
    volumes:
      - ${HOME}/app/minio/data:/data

  consul:
    image: docker.io/bitnami/consul:latest
    ports:
      - "8300:8300"
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - app-tier
    environment:
      - CONSUL_BIND_INTERFACE='eth0'
      - CONSUL_AGENT_MODE=server
      - CONSUL_ENABLE_UI=true
      - CONSUL_BOOTSTRAP_EXPECT=1
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0

  jaeger:
    image: docker.io/jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    networks:
      - app-tier
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true

  redis:
    image: docker.io/bitnami/redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-tier
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=123456
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    volumes:
      - ${HOME}/app/redis:/bitnami/redis/data
      - /etc/localtime:/etc/localtime

  core-service:
    image: kratos-cms/core-service:0.1.0
    networks:
      - app-tier

  front-service:
    image: kratos-cms/front-service:0.1.0
    networks:
      - app-tier

  admin-service:
    image: kratos-cms/admin-service:0.1.0
    networks:
      - app-tier