version: '3'
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_BROKER_ID=1
    volumes:
      - /home/data/kafka:/bitnami/kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper
  postgres:
    image: docker.io/bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=accesscontroldb
  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=123456789
      - MINIO_DEFAULT_BUCKETS=my-bucket
      - MINIO_FORCE_NEW_KEYS=yes
      - BITNAMI_DEBUG=true
  consul:
    image: docker.io/bitnami/consul:latest
    ports:
      - "8300:8300"
      - "8500:8500"
      - "8600:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE='eth0'
      - CONSUL_AGENT_MODE=server
      - CONSUL_ENABLE_UI=true
      - CONSUL_BOOTSTRAP_EXPECT=1
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
  jaeger:
    image: docker.io/jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
  redis:
    image: docker.io/bitnami/redis:latest
    ports:
      - "6379:6379"
  user-service:
    image: kratos-cms/user-service:0.1.0
  file-service:
    image: kratos-cms/file-service:0.1.0
  content-service:
    image: kratos-cms/content-service:0.1.0
  comment-service:
    image: kratos-cms/comment-service:0.1.0
  admin-service:
    image: kratos-cms/admin-service:0.1.0