server:
  grpc:
    addr: "0.0.0.0:0"
    timeout: 10s
    middleware:

client:
  grpc:
    timeout: 10s
    middleware:
      enable_logging: true
      enable_recovery: true
      enable_tracing: true
      enable_validate: true
      enable_circuit_breaker: true
      auth:
        method: ""
        key: "some_api_key"
